export const sectionPolicy = [
  ['Tabs', 11, 'universal'],
  ['Backslash escapes', 13, 'universal'],
  ['Entity and numeric character references', 17, 'universal'],
  ['Precedence', 1, 'universal'],
  ['Thematic breaks', 19, 'semantic'],
  ['ATX headings', 18, 'semantic'],
  ['Setext headings', 27, 'excluded'],
  ['Indented code blocks', 12, 'excluded'],
  ['Fenced code blocks', 29, 'semantic'],
  ['HTML blocks', 44, 'excluded'],
  ['Link reference definitions', 27, 'excluded'],
  ['Paragraphs', 8, 'universal'],
  ['Blank lines', 1, 'universal'],
  ['Block quotes', 25, 'semantic'],
  ['List items', 48, 'semantic'],
  ['Lists', 26, 'semantic'],
  ['Inlines', 1, 'universal'],
  ['Code spans', 22, 'semantic'],
  ['Emphasis and strong emphasis', 132, 'semantic'],
  ['Links', 90, 'semantic'],
  ['Images', 22, 'excluded'],
  ['Autolinks', 19, 'excluded'],
  ['Raw HTML', 20, 'excluded'],
  ['Hard line breaks', 15, 'excluded'],
  ['Soft line breaks', 2, 'universal'],
  ['Textual content', 3, 'universal']
].map(([section, count, treatment]) => ({ section, count, treatment }));
